### ISSUE TITLE
Don't work as expected with lxterminal

### ISSUE THREAD

**Issue by SmartFinn** [SmartFinn/eve-ng-integration#11]
> @k0ste wrote:
>
> Hello.
> One arg with 'command' not work with lxterminal, open lxtermianal without telnet session.
> 
> Not work:
> ```python
> ['lxterminal', '-e', 'telnet 192.168.0.214 32769']
> ```
>
> Work as expected:
>
> ```python
> ['lxterminal', '-e', 'telnet', '192.168.0.214', '32769']
> ```
> ```shell
> [k0ste@WorkStation ~]$ lxterminal --version
> lxterminal 0.3.0
> [k0ste@WorkStation ~]$ 
> ```

Moved from #10

**Comment by k0ste** [comment]
What is your proposal for solving this problem?

**Comment by SmartFinn** [comment]
I plan to change command to `<terminal> --command="telnet <server> <port>"`. It's need to test a lot of terminal emulators to support the option.

**Comment by rusty725** [comment]
Hi, is it possible to integrate deepin-terminal ?

**Comment by SmartFinn** [comment]
lxterminal fixed the weird behavior for `-e` options a long time ago.
