### ISSUE TITLE
Capture with Wireshark stopped working after upgrade to Fedora 26

### ISSUE THREAD

**Issue by etem** [SmartFinn/eve-ng-integration#13]
Hello, 
Capture with wireshark is no longer working after upgrade to Fedora 26. Nothing happens when I select capture interface. 

Wireshark is installed on the system and is working fine outside of EVE.

```
➜  ~ dnf list installed | grep -i wireshark
wireshark.x86_64                       2.2.7-1.fc26                @fedora      
wireshark-cli.x86_64                   2.2.7-1.fc26                @fedora      
wireshark-gtk.x86_64                   2.2.7-1.fc26                @fedora      
wireshark-qt.x86_64                    2.2.7-1.fc26                @fedora      
➜  ~ 

```

**Comment by etem** [comment]
Update - I was able to fix that by [appending](https://github.com/etem/eve-ng-integration/commit/c63150f50ab713326d3ed30f706ef11cee0d55fb) *-gtk* to wireshark command at script line 80 but not sure if that will work on other distros too.

**Comment by SmartFinn** [comment]
Hello.

Works fine on a fresh install of Fedora 26. Looks like `/usr/bin/wireshark` symlink is missing after the upgrade.

Try to create the symlink using the following command:

```sh
sudo update-alternatives --auto wireshark

# check the symlink
ls -l /usr/bin/wireshark
```

BTW, wireshark-gtk is deprecated https://blog.wireshark.org/2013/10/switching-to-qt/
