### ISSUE TITLE
running issues on MAC

### ISSUE THREAD

**Issue by rajpathak1983** [SmartFinn/eve-ng-integration#14]
i am getting following issue while running it on MAC. could you please help?
RAJPPATH-M-V331:~ rajppath$ ls -l eve-ng-integration/
total 2480
-rw-r--r--  1 rajppath  staff     1082 Jul 13 18:48 LICENSE
-rw-r--r--  1 rajppath  staff     1656 Jul 13 18:48 Makefile
-rw-r--r--  1 rajppath  staff     3886 Jul 13 18:48 README.md
-rwxr-xr-x@ 1 rajppath  staff     7680 Jul 14 12:12 Thumbs.db
drwxr-xr-x  5 rajppath  staff      170 Jul 13 18:48 debian
-rw-r--r--  1 rajppath  staff  1236260 Jul 13 18:48 demo.gif
-rw-r--r--  1 rajppath  staff     3280 Jul 13 18:48 eve-ng-integration
-rw-r--r--  1 rajppath  staff      267 Jul 13 18:48 eve-ng-integration.desktop
-rw-r--r--  1 rajppath  staff     2946 Jul 13 18:48 install.sh
RAJPPATH-M-V331:~ rajppath$ 
RAJPPATH-M-V331:~ rajppath$ 
RAJPPATH-M-V331:~ rajppath$ cd eve-ng-integration/eve-ng-integration-master
-bash: cd: eve-ng-integration/eve-ng-integration-master: No such file or directory
RAJPPATH-M-V331:~ rajppath$ 
RAJPPATH-M-V331:~ rajppath$ sudo make install post-install
Password:
make: *** No rule to make target `install'.  Stop.
RAJPPATH-M-V331:~ rajppath$

**Comment by SmartFinn** [comment]
```
RAJPPATH-M-V331:~ rajppath$ cd eve-ng-integration/eve-ng-integration-master
-bash: cd: eve-ng-integration/eve-ng-integration-master: No such file or directory
```

The correct command is  `cd eve-ng-integration`

**Comment by rajpathak1983** [comment]
Tried that as well.

RAJPPATH-M-V331:eve-ng-integration rajppath$ sudo make install post-install
Password:
install -m 755 -D -t /usr/bin/ eve-ng-integration
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
RAJPPATH-M-V331:eve-ng-integration rajppath$

**Comment by rajpathak1983** [comment]
When i clone git, i can see below files and dir in eve-ng-integration folder.

RAJPPATH-M-V331:eve-ng-integration rajppath$ ls
LICENSE                         README.md                       debian                          eve-ng-integration              install.sh
Makefile                        Thumbs.db                       demo.gif                        eve-ng-integration.desktop
RAJPPATH-M-V331:eve-ng-integration rajppath$ pwd
/Users/rajppath/eve-ng-integration
RAJPPATH-M-V331:eve-ng-integration rajppath$ 
eve-ng-integration-master dir is not present.

cd eve-ng-integration/eve-ng-integration-master

i tried to run sudo make install post-install from /Users/rajppath/eve-ng-integration folder but its throwing errors  as below:- 
RAJPPATH-M-V331:eve-ng-integration rajppath$ sudo make install post-install
Password:
install -m 755 -D -t /usr/bin/ eve-ng-integration
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
not sure what to do to fix it?

**Comment by SmartFinn** [comment]
Oh, I used to think that you installed Linux-distro on your MacBook.

**eve-ng-integration** supports Linux distros only and can't work on macOS because of use Linux-specific `xdg-utils`.
