### ISSUE TITLE
Issues with wireshark-qt on Fedora 26

### ISSUE THREAD

**Issue by jtmajorx** [SmartFinn/eve-ng-integration#16]
Made a symbolic link to point /usr/bin/Wireshark to /usr/bin/Wireshark-qt. So Wireshark launches when you start a capture, but I'm not seeing any data. Just an empty capture.

**Comment by SmartFinn** [comment]
It seems to me it's related to ssh-askpass. Make sure that ssh-askpass is work correctly:

```sh
setsid ssh root@EVE_NG_IP sh -c 'echo; hostname; exit'

# replace EVE_NG_IP to ip address of EVE-NG computer
# should get hostname of EVE-NG machine in response
```

If you have problem with that, try to install ssh-askpass via the command:

```sh
sudo dnf install -y openssh-askpass
```

**Comment by jtmajorx** [comment]
setsid prompts for password, but I do get hostname back. Still, no packets showing up in capture though.

**Comment by SmartFinn** [comment]
Do you have the same password prompt when you start the capture?
