### ISSUE TITLE
Doesn't work on Ubuntu 16.04, firefox 56

### ISSUE THREAD

**Issue by stminm** [SmartFinn/eve-ng-integration#18]
Installed eve-ng-integration 0.4.1-0 on Ubuntu 16.04.3 LTS with Firefox 56.
When accessing a running node I got this: "Firefox doesn’t know how to open this address, because one of the following protocols (telnet) isn’t associated with any program or is not allowed in this context."
Couldn't find telnet, capture or docker in Preferences → Applications.
Tried logout/login and reboot.
Chrome on the same machine is working fine.

**Comment by SmartFinn** [comment]
[Firefox says `The address wasn't understood` when you clicked on a device](https://github.com/SmartFinn/eve-ng-integration#firefox-says-the-address-wasnt-understood-when-you-clicked-on-a-device)
