### ISSUE TITLE
Making SecureCRT the default

### ISSUE THREAD

**Issue by TheNetworker** [SmartFinn/eve-ng-integration#19]
Thank you for maintaining and developing this repo. Would you please guide me through on how to use SecureCRT (installed on linux) to be the default terminal that open when you click on device instead of default one?

Thanks

**Comment by SmartFinn** [comment]
SecureCRT cannot be used as Linux terminal emulator, but you can make a wrapper that replacing telnet command:

```sh
echo '#!/bin/sh\nSecureCRT /T /TELNET "$@"' > ~/.local/bin/telnet
chmod +x ~/.local/bin/telnet
```

Make sure that `$HOME/.local/bin` exist in your PATH. If this not true then add this line to your `~/.profile` file and then log out and log back:

```sh
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```

**Comment by SmartFinn** [comment]
Another way is to use this fork https://github.com/jkldgoefgkljefogeg/eve-ng-integration

**Comment by dlj2019** [comment]
Thank you for all of the hard work already provided!

Would you be able to help to get Securecrt working on Manjaro?... I already tried the instructions provided but still not working ...

![deepinscreenshot_select-area_20171228192902](https://user-images.githubusercontent.com/30886694/34426528-a085e9ba-ec05-11e7-9866-866e8a1cf5e0.png)

Thanks in advance!

DJ

**Comment by SmartFinn** [comment]
@dlj2019 my fault. The command for bash should looks like:

```sh
echo -e '#!/bin/sh\nSecureCRT /T /TELNET "$@"' > ~/.local/bin/telnet
chmod +x ~/.local/bin/telnet
```

**Comment by dlj2019** [comment]
For some reason still not working...

![deepinscreenshot_select-area_20171229120302](https://user-images.githubusercontent.com/30886694/34442456-51f4ccd6-ec90-11e7-881a-4304d8f09a3c.png)

Should i make modifications to the "eve-ng-integration.desktop" file?

![deepinscreenshot_select-area_20171229120936](https://user-images.githubusercontent.com/30886694/34442613-47ddea10-ec91-11e7-89f5-20edb9bbeba3.png)

**Comment by SmartFinn** [comment]
@dlj2019 make sure that ~/.local/bin/telnet has executable bit `chmod +x ~/.local/bin/telnet` if it's true add the line to ~/.profile file and than reboot your laptop:

```sh
echo 'PATH="$HOME/bin:$HOME/.local/bin:$PATH"' >> ~/.profile
```

**Comment by dlj2019** [comment]
It works. Awesome!!!

Your are the Best ... thanks again for all the hard work provided.

Regards,
DJ

**Comment by dlj2019** [comment]
I only see that Tilix also opens along with Securecrt , is there a way to fix it or its not possible ?

**Comment by shotab** [comment]
if anyone still looking  how to use SecureCRT, there is another solution.

echo -e '#!/bin/sh\nSecureCRTx /T /TELNET $1 $2' > ~/.local/bin/SecureCRTx
chmod +x ~/.local/bin/SecureCRTx

next update ~/.profile 
PATH="$HOME/bin:$HOME/.local/bin:$PATH"

edit following script as it is on picture below /usr/bin/eve-ng-integration
https://transfer.sh/gH4Tz/1.png
https://transfer.sh/bOcOn/2.png

**Comment by dlj2019** [comment]
Thanks...

Can you please tell me how do i get Tilix to work with Eve-NG? i need to
open different "Tab"sessions instead new windows. Would the information
below work ?

 [Desktop Entry]
Name=EVE-NG Integration
*Exec=env OVERRIDE_TERMINAL_CMD="tilix --tab -e" eve-ng-integration %u *

If so what's the next steps?

Thanks in advance!

**Comment by shotab** [comment]
> Thanks...
> 
> Can you please tell me how do i get Tilix to work with Eve-NG? i need to
> open different "Tab"sessions instead new windows. Would the information
> below work ?
> 
>  [Desktop Entry]
> Name=EVE-NG Integration
> *Exec=env OVERRIDE_TERMINAL_CMD="tilix --tab -e" eve-ng-integration %u *
> 
> If so what's the next steps?
> 
> Thanks in advance!

I do not use Tilix so I am not familiar with it. 
do you mean something like this one ? 
https://mega.nz/#!344ySBDD!yDfJP06lqmNWQpZQkSoRUloNHzuqnKcT4EFTxO_zKKg

**Comment by dlj2019** [comment]
Yes, that's exactly what i need ... Do you know how i can this done?

**Comment by shotab** [comment]
> Yes, that's exactly what i need ... Do you know how i can this done?

This is how I did it, maybe there is better solution which I don't know. 

**create following script and make it executable:** 
```
echo -e '#!/bin/bash\ntilix -a app-new-session $@' > ~/.local/bin/tilixx
chmod +x ~/.local/bin/tilixx
```

next you must edit "/usr/bin/eve-ng-integration" script  and add following code as it is on picture below:

```
elif self._is_command('tilixx'):
  return ['tilixx', '-e']
```
  
https://transfer.sh/aCHYk/tilix1.png
https://transfer.sh/M2qwi/tilix2.png

**Comment by dlj2019** [comment]
I am new to Linux.... Executable file has been created but i still not able
to open Tilix.

[Desktop Entry]
Name=EVE-NG Integration
Exec=eve-ng-integration %u
TryExec=eve-ng-integration
Type=Application
Categories=Network;
MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
X-KDE-Protocols=telnet,capture,docker
NoDisplay=true
def_terminal_emulator_cmd(self):
   if self.override_terminal:
       return self.override_terminal.split()
   elif self._is_command('tilixx'):
       return ['tilixx', '-e']
   elif url.scheme == 'telnet':
       cmd = 'telnet {host} {port}'.format(**data)

**Comment by shotab** [comment]
> I am new to Linux.... Executable file has been created but i still not able
> to open Tilix.
> 
> [Desktop Entry]
> Name=EVE-NG Integration
> Exec=eve-ng-integration %u
> TryExec=eve-ng-integration
> Type=Application
> Categories=Network;
> MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
> X-KDE-Protocols=telnet,capture,docker
> NoDisplay=true
> def_terminal_emulator_cmd(self):
>    if self.override_terminal:
>        return self.override_terminal.split()
>    elif self._is_command('tilixx'):
>        return ['tilixx', '-e']
>    elif url.scheme == 'telnet':
>        cmd = 'telnet {host} {port}'.format(**data)

here is video.
https://mega.nz/#!j9ZiCYLa!CwFGrcaWN7bDS9C0qIJRfcR7p51k4SvTnErHNp0jA70

**Comment by dlj2019** [comment]
I am using KDE Neon on XPS 15.
 usr/share/application/eve-ng-integration.desktop.

The Eve-ng integration.desktop differs from what i have. Should replace
below files with the ones in the website?

eni-rdp-wrapper
<https://github.com/SmartFinn/eve-ng-integration/blob/master/bin/eni-rdp-wrapper>
Add
RDP wrapper
<https://github.com/SmartFinn/eve-ng-integration/commit/9d39dc93a33faee3aa0e3396d17d001e15dac7c9>
 #7 <https://github.com/SmartFinn/eve-ng-integration/issues/7> 3 months ago
eve-ng-integration
<https://github.com/SmartFinn/eve-ng-integration/blob/master/bin/eve-ng-integration>
Move
files and update installation scripts
<https://github.com/SmartFinn/eve-ng-integration/commit/ed9c6693b9236b37d6532326928f23cd4e5336b7>
3
months ago

**Comment by dlj2019** [comment]
hi shotab,

Can you please let me know the 2 steps needed (link is not working anymore?

https://transfer.sh/gH4Tz/1.png
https://transfer.sh/bOcOn/2.png

============================================================  
"if anyone still looking how to use SecureCRT, there is another solution.

echo -e '#!/bin/sh\nSecureCRT /T /TELNET $1 $2' > ~/.local/bin/SecureCRTx
chmod +x ~/.local/bin/SecureCRTx

next update ~/.profile
PATH="$HOME/bin:$HOME/.local/bin:$PATH"

### **edit following script as it is on picture below /usr/bin/eve-ng-integration
https://transfer.sh/gH4Tz/1.png
https://transfer.sh/bOcOn/2.png
================= "==========================================

**Comment by dlj2019** [comment]
> if anyone still looking how to use SecureCRT, there is another solution.
> 
> echo -e '#!/bin/sh\nSecureCRT /T /TELNET $1 $2' > ~/.local/bin/SecureCRTx
> chmod +x ~/.local/bin/SecureCRTx
> 
> next update ~/.profile
> PATH="$HOME/bin:$HOME/.local/bin:$PATH"
> 
> edit following script as it is on picture below /usr/bin/eve-ng-integration
> https://transfer.sh/gH4Tz/1.png
> https://transfer.sh/bOcOn/2.png

Can you please let me know the last 2 steps ( png pictures) missing. The 2 links are no longer available.

https://transfer.sh/gH4Tz/1.png
https://transfer.sh/bOcOn/2.png

Thanks a lot in advance!

Regards,
DJ

**Comment by shotab** [comment]
hi, 
you should edit "eve-ng-integration" script, in my case it is located in 
/usr/bin/eve-ng-integration

and here is changes you should make

https://ibb.co/esgSpK
https://ibb.co/cwdU3e

**Comment by dlj2019** [comment]
Excellent !!!! 

Thanks a lot !!!

**Comment by kebeeyong** [comment]
How do I integrate putty with eve-ng on ubuntu
