### ISSUE TITLE
Packet capture not working on Fedora 27

### ISSUE THREAD

**Issue by etem** [SmartFinn/eve-ng-integration#20]
Hello, 
Packet capture with Wireshark is not working on Fedora 27. 
Every time I click on "capture" Wireshark is loading fine but I only see a blank screen without any packet captures.

**Comment by SmartFinn** [comment]
Hi,
Wireshark prompts for a password? Try commands from that comment https://github.com/SmartFinn/eve-ng-integration/issues/16#issuecomment-318871310

**Comment by etem** [comment]
Hi @SmartFinn . Yes, ssh-askpass seems to be working fine.

**Comment by SmartFinn** [comment]
Just tested on Fedora 27 and the capture works as expected. I had a problem with askpass, but with key-based authentication everything works:

![screenshot from 2017-12-04 15-12-36](https://user-images.githubusercontent.com/819186/33554514-b2b2e6f0-d905-11e7-9d44-35297b4b59e5.png)

**Comment by etem** [comment]
Thanks. I will try that using SSH key authentication and let you know.

**Comment by etem** [comment]
Indeed it's working with key authentication. 
Thank you @SmartFinn . Appreciate your help!

**Comment by SmartFinn** [comment]
Thanks for testing. I'll add a note about it in README asap.

**Comment by SmartFinn** [comment]
I added setsid to ssh command, and this issue is fixed now.
