### ISSUE TITLE
Will there be support for Mac?

### ISSUE THREAD

**Issue by Vegarhalo** [SmartFinn/eve-ng-integration#21]

**Comment by SmartFinn** [comment]
Nope, eve-ng-integration uses Linux-specific `xdg-utils`.

**Comment by dlasher** [comment]
Looks like xdg-utils exist for OSX.. xquartz ties it together.

- https://enthusiastscomputer.blogspot.com/2014/01/how-do-i-use-xdg-open-from-xdg-utils-on.html
- https://github.com/benjaminoakes/utilities/blob/master/osx/xdg-open
- https://github.com/macports/macports-ports/tree/master/sysutils/xdg-utils

**Comment by SmartFinn** [comment]
It looks dubious. The main issue that must be resolved is registration the protocol handlers. Anyway, I don't have a plan and a possibility to support OS X. Will be great if someone made a fork.
