### ISSUE TITLE
помогите

### ISSUE THREAD

**Issue by re2play** [SmartFinn/eve-ng-integration#22]
можно ли установить eve-ng на дебиан систему?
хочу установить на физическую машину,  все сделал как описано в eve-ng.net  bare install, так же сделал по ваше описанию.
делаю ребут загружается  ос без изменений, не могу понять как запустить, можете объяснить?
а есть веб версия eve-ng?, так же не пойму как она запускается?

**Comment by SmartFinn** [comment]
Этот проект имеет косвеное отношение к EVE-NG и использовал его только в виде образа для VM, поэтому подсказать ничего не могу. Могу только привлечь внимание на пункт:

> 14. Close your session and re-Login with **root** user to the EVE and follow the setup wizard
