### ISSUE TITLE
Sorry but Not working on Manjaro...hope you can help me out!

### ISSUE THREAD

**Issue by dlj2019** [SmartFinn/eve-ng-integration#23]
Hi,

I already install eve-ng-integration v4.1 and now v5.0 released 2 day ago but no success :(
During installation i did not face any issues during the script.

  Operating System: Manjaro Linux
            Kernel: Linux 4.9.68-1-MANJARO
            Architecture: x86-64

When i click on host to open the console, nothing comes up :(

I hope you can help me out .

Thanks in advance.
DJ

**Comment by SmartFinn** [comment]
What actually didn't work? Telnet? Try to run the command and let me know what you got:

```
xdg-open 'telnet://route-server.he.net'
```

**Comment by dlj2019** [comment]
Unfortunately, nothing shows up...i don't even have an option to choose the application to open.

In Chrome

In firefox

**Comment by SmartFinn** [comment]
In this case, see [Click on a node does not open an app (opens another app) in all browsers](https://github.com/SmartFinn/eve-ng-integration#click-on-a-node-does-not-open-an-app-opens-another-app-in-all-browsers)

**Comment by dlj2019** [comment]
what should i do with the below info:

mkdir -p ~/.local/share/applications/
xdg-mime default eve-ng-integration.desktop x-scheme-handler/capture
xdg-mime default eve-ng-integration.desktop x-scheme-handler/telnet
xdg-mime default eve-ng-integration.desktop x-scheme-handler/docker
xdg-mime default eni-rdp-wrapper.desktop application/x-rdp

i have this info in ~/.local/share/applications/

appimagekit-Etcher.desktop
chrome-aohghmighlieiainnegkcijnfilokake-Default.desktop
chrome-apdfllckaahabafndbhieahigkjlhalf-Default.desktop
chrome-blpcfgokakmgnkcojhhkbfbldkacnbeo-Default.desktop
chrome-pjkljhegncpnkpknbcohdijeoejaedia-Default.desktop
mimeapps.list
mimeinfo.cache

Thanks in advance !

**Comment by dlj2019** [comment]
Should i Enter it to the "eve-ng-integration.desktop "file ?

[Desktop Entry]
Name=EVE-NG Integration
Exec=eve-ng-integration %u
TryExec=eve-ng-integration
Type=Application
Categories=Network;
MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
X-KDE-Protocols=telnet,capture,docker
NoDisplay=true

**Comment by SmartFinn** [comment]
No, you should execute the following commands line by line in your terminal:

```
mkdir -p ~/.local/share/applications/
xdg-mime default eve-ng-integration.desktop x-scheme-handler/capture
xdg-mime default eve-ng-integration.desktop x-scheme-handler/telnet
xdg-mime default eve-ng-integration.desktop x-scheme-handler/docker
xdg-mime default eni-rdp-wrapper.desktop application/x-rdp
```

**Comment by dlj2019** [comment]
Thanks but that's what i have done for about 10 times. I get no errors but nothing changes :(

**Comment by SmartFinn** [comment]
What this command returns:

```
xdg-mime query default x-scheme-handler/telnet
```

and what happens when running:

```
xdg-open 'telnet://route-server.he.net'
```

Could you run those commands and paste the screenshot here?

**Comment by dlj2019** [comment]
Sure ... this is what i got

**Comment by SmartFinn** [comment]
No screenshot here ;)

**Comment by dlj2019** [comment]
didn't you get the Screenshot ?

**Comment by SmartFinn** [comment]
No, try to drop into GitHub comment field instead of email.

**Comment by dlj2019** [comment]
i will definitely upload some detailed information there today. I thing i found out why i was not getting the terminal. I believe it was because i didn't not have Gnome-terminall installed but Tilix.

Do you know do i redirect to open the terminal using Securecrt instead Gnome ?

Thanks for all your help.... i just love this tool , is great ! ( i just want to get everything to work with Linux).

As i said, i will send you more information into GitHub sometime today

**Comment by SmartFinn** [comment]
You can use any terminal emulator, including Tilix, see this https://github.com/SmartFinn/eve-ng-integration/issues/6#issuecomment-281147424

SecureCRT isn't a terminal emulator, but you can use it as telnet command replacement, see https://github.com/SmartFinn/eve-ng-integration/issues/19#issuecomment-346646342

**Comment by dlj2019** [comment]
Thanks for the info Sergei... But i can open only one console window, if i try to open a second terminal window it will close the first one.

**Comment by dlj2019** [comment]
Also, any ideia how i can get Wireshark to work properly ? 

This is the error i am getting it. 

![ss1](https://user-images.githubusercontent.com/30886694/34321002-004a23de-e7d3-11e7-89a6-8fd2bca9a0b9.jpg)

**Comment by SmartFinn** [comment]
>But i can open only one console window, if i try to open a second terminal window it will close the first one.

Try this eve-ng-integration.destop file:

```
[Desktop Entry]
Name=EVE-NG Integration
Exec=env OVERRIDE_TERMINAL_CMD="tilix -e" eve-ng-integration %u
TryExec=eve-ng-integration
Type=Application
Categories=Network;
MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
X-KDE-Protocols=telnet,capture,docker
NoDisplay=true
```
Just testing it works as exepted with Tilix.


> Also, any ideia how i can get Wireshark to work properly ?
> This is the error i am getting it.

That not an error. That is ssh-askpass ask you to enter the root password for EVE-NG machine.

**Comment by dlj2019** [comment]
1- Tilix opens but not " Tab" windows

2- When i press ok to continue with wireshark, i doesn't finish opening the application

**Comment by dlj2019** [comment]
Tilix is now good!

Need to fix Wireshark :)

**Comment by dlj2019** [comment]
Here is what happens when i press ok...

![deepinscreenshot_select-area_20171223114614](https://user-images.githubusercontent.com/30886694/34321180-fe19ae32-e7d6-11e7-9e4c-49c07f7b97d4.png)

**Comment by SmartFinn** [comment]
> 1 - Tilix opens but not " Tab" windows

Tilix doesn't support opening new tab via command line.

> Need to fix Wireshark :)
> Here is what happens when i press ok...

See [Error End of file on pipe magic during open when starting Wireshark](https://github.com/SmartFinn/eve-ng-integration#error-end-of-file-on-pipe-magic-during-open-when-starting-wireshark)

In brief, the problem with ssh authentification. You could setup SSH key-based authentification with EVE-NG VM to avoid the problem.

**Comment by dlj2019** [comment]
i already have "x11-ssh-askpass " installed.

**Comment by SmartFinn** [comment]
I see but Wireshark not getting data through ssh, so it's problem with authentification.

**Comment by dlj2019** [comment]
Do you know how i can fix this authentication issue. I installed "openssh-askpass" but the issue still there...

![deepinscreenshot_select-area_20171223120126](https://user-images.githubusercontent.com/30886694/34321287-40118cf4-e7d9-11e7-8d56-fb93dcffc9b1.png)

**Comment by SmartFinn** [comment]
As I wrote, try to set SSH key-based authentification.

Generate new key if you didn't have it:

```
ssh-keygen -t rsa
```

and then upload it to EVE-NG:

```
ssh-copy-id root@EVE_NG_IP
```

**Comment by dlj2019** [comment]
New RSA was genarated and successfully uploaded to the EVE-NG Server but i still have the same issue:

" /usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh 'root@ x.x.x.x'"
and check to make sure that only the key(s) you wanted were added. "

**Comment by SmartFinn** [comment]
I can't help you with the problem. Try to debug the case with this command:

```
ssh -l root x.x.x.x tcpdump -i pnet0 -n -s 0 -U -w - | wireshark -k -i -
```

**Comment by dlj2019** [comment]
[dee@dee-dlj ~]$ ssh -l root x.x.x.x tcpdump -i pnet0 -n -s 0 -U -w - | wireshark -k -i -
qt5ct: using qt5ct plugin
ssh: Could not resolve hostname x.x.x.x: Name or service not known
qt5ct: D-Bus global menu: no

and it opens with wireshare with the error posted before ( " end of file on pipe magic during open")

**Comment by SmartFinn** [comment]
You didn't replace `x.x.x.x` with your EVE-NG ip.

**Comment by dlj2019** [comment]
i did...

[dee@dee-dlj ~]$ ssh -l root 192.168.1.85 tcpdump -i pnet0 -n -s 0 -U -w - | wireshark -k -i -
qt5ct: using qt5ct plugin
sign_and_send_pubkey: signing failed: agent refused operation
root@x.x.x.x's password: qt5ct: D-Bus global menu: no

tcpdump: listening on pnet0, link-type EN10MB (Ethernet), capture size 262144 bytes

**Comment by SmartFinn** [comment]
> sign_and_send_pubkey: signing failed: agent refused operation

You have a problem with ssh-agent. Reboot your host and try again.

> root@x.x.x.x's password: qt5ct: D-Bus global menu: no

Still, ask the password...

**Comment by dlj2019** [comment]
i reboot the laptop and the server and tried again...

[dee@dee-dlj ~]$ ssh root@192.168.1.85 tcpdump -i pnet0 -n -s 0 -U -w - | wireshark -k -i -
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
tcpdump: listening on pnet0, link-type EN10MB (Ethernet), capture size 262144 bytes

You are the Best !!! Thank you so much for all your help... i ready appreciate it .
