### ISSUE TITLE
Unable to find a shell with Terminator

### ISSUE THREAD

**Issue by SanderDelden** [SmartFinn/eve-ng-integration#33]
I'm running Terminator 1.91 and running in to the issue using both Firefox & Chrome. When starting a session on EVE-NG it just opens a Terminator screen showing `Unable to find a shell` 

Please let me know if any additional information/logging should be provided

**Comment by SmartFinn** [comment]
Do you use Debian-based distro? Do you set Terminator as default for your session or edit eve-ng-integration/eve-ng-integration.desktop file?

Is this `x-terminal-emulator -e telnet route-server.he.net` command opens Terminator with telnet session?

**Comment by SanderDelden** [comment]
Yes I'm running Ubuntu 18.04. Terminator is my default terminal.
The command opens Terminator and connects to the Telnet host without anny issues.

**Comment by SmartFinn** [comment]
Terminator has weird behavior when it is launched as `x-terminal-emulator`:

```
-e, --command=COMMAND
       Runs  the specified command instead of your default shell or profile specified com‐
       mand. Note: if Terminator is launched as x-terminal-emulator -e  behaves  like  -x,
       and the longform becomes --execute2=COMMAND
```

To override it run the following commands:

```sh
mkdir -p ~/.local/share/applications/
cp -f /usr/share/applications/eve-ng-integration.desktop ~/.local/share/applications/
sed -i 's/^Exec=/&env OVERRIDE_TERMINAL_CMD="terminator -e" /' ~/.local/share/applications/eve-ng-integration.desktop
```

**Comment by SanderDelden** [comment]
Unfortunately this does not work, now no Terminator window is openend

**Comment by SmartFinn** [comment]
Check ~/.local/share/applications/eve-ng-integration.desktop file, it should contains:

```ini
[Desktop Entry]
Name=EVE-NG Integration
Exec=env OVERRIDE_TERMINAL_CMD="terminator -e" eve-ng-integration %u
TryExec=eve-ng-integration
Type=Application
Categories=Network;
MimeType=x-scheme-handler/telnet;x-scheme-handler/capture;x-scheme-handler/docker;
X-KDE-Protocols=telnet,capture,docker
NoDisplay=true
```

Also, see and run commands from [Click on a node does not open an app (opens another app) in all browsers](https://github.com/SmartFinn/eve-ng-integration#click-on-a-node-does-not-open-an-app-opens-another-app-in-all-browsers)

**Comment by SanderDelden** [comment]
This worked, thank you for the help!
