### ISSUE TITLE
How can I change my default terminal application?

### ISSUE THREAD

**Issue by Nand087** [SmartFinn/eve-ng-integration#36]
Is there a way to choose my default terminal application?
Also, how can I get eve-ng to **open tabs** instead of new terminal **windows** when I console to a device?
Thanks for your help.
Fernando

**Comment by SmartFinn** [comment]
There is an example for ROXTerm https://github.com/SmartFinn/eve-ng-integration/issues/6#issuecomment-281147424

> Also, how can I get eve-ng to open tabs instead of new terminal windows when I console to a device?

Only in case your terminal emulator able to run commands in a new tab. It works with ROXTerm well.

**Comment by Nand087** [comment]
Thank you for your help @SmartFinn. This is what I did to make it work with _Konsole_:

1. `sudo vim /usr/share/applications/eve-ng-integration.desktop`
2. `Exec=env OVERRIDE_TERMINAL_CMD="konsole --new-tab -e" eve-ng-integration %u`

**Comment by ctfalci** [comment]
> Thank you for your help @SmartFinn. This is what I did to make it work with _Konsole_:
> 
> 1. `sudo vim /usr/share/applications/eve-ng-integration.desktop`
> 2. `Exec=env OVERRIDE_TERMINAL_CMD="konsole --new-tab -e" eve-ng-integration %u`

Hi, I made I stupid mistake. I had followed your 'tut', however, I didn't realize one simple thing, 'KONSOLE' isn't my default terminal.
I am using pop-os and 'TERMINAL + OhmyZSH' (not yelling) is my default app, before made the changes when clicked on the topology of a router e.g., I could open the XDG, now it pops on the screen, however, doesn't open when clicked. Is there a way to fix the original settings?

**Comment by SmartFinn** [comment]
I don't clearly understand the original settings of what. If you told about eve-ng-integration desktop-file than just reinstall it with [install.sh](https://github.com/SmartFinn/eve-ng-integration#install-script) to restore /usr/share/applications/eve-ng-integration.desktop

**Comment by ctfalci** [comment]
> I don't clearly understand the original settings of what. If you told about eve-ng-integration desktop-file than just reinstall it with [install.sh](https://github.com/SmartFinn/eve-ng-integration#install-script) to restore /usr/share/applications/eve-ng-integration.desktop

Sorry if wasn't clear . Got ya! BTW, I've installed "konsole" to use with chrome, all working fine now! cheers

**Comment by samuelthapa** [comment]
@ctfalci Thanks, it worked with xfce4. Now i don't have to search for secure-CRT app keys

**Comment by W4t3VR** [comment]
@SmartFinn i tried with alacritty but didn't work
