### ISSUE TITLE
Click on a node does not open 

### ISSUE THREAD

**Issue by fayooo** [SmartFinn/eve-ng-integration#38]
Hello,

When I click on a node then choose Eve-NG Integration from the Launch application window does not open the shell either with Firefox or Google chrome.

I am using Linux Red Hat 8.3.

Thanks in advance

**Comment by SmartFinn** [comment]
See https://github.com/SmartFinn/eve-ng-integration#click-on-a-node-does-not-open-an-app-opens-another-app-in-all-browsers

**Comment by fayooo** [comment]
hello SmartFinn

Thanks a lot for your reply

I already followed all steps mentioned in the link and also I tried all steps in know problems but still I have a problem either if use Firefox or Google Chrome I click on the node then choose  Eve-NG Integration from the Launch application it does not open the telnet (Shell).

 Regards,

**Comment by SmartFinn** [comment]
What happens when runs the command:

```
xdg-open 'telnet://route-server.he.net'
```

**Comment by fayooo** [comment]
> `xdg-open 'telnet://route-server.he.net'`

the output:

vayoo@vayoo ~]$ sudo xdg-open 'telnet://route-server.he.net'
/usr/bin/env: ‘python’: No such file or directory
/bin/xdg-open: line 862: x-www-browser: command not found
Failed to open connection to "session" message bus: /usr/bin/dbus-launch terminated abnormally with the following error: No protocol specified
Autolaunch error: X11 initialization failed.

Running without a11y support!
No protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0
/bin/xdg-open: line 862: iceweasel: command not found
/bin/xdg-open: line 862: seamonkey: command not found
/bin/xdg-open: line 862: mozilla: command not found
/bin/xdg-open: line 862: epiphany: command not found
/bin/xdg-open: line 862: konqueror: command not found
/bin/xdg-open: line 862: chromium: command not found
/bin/xdg-open: line 862: chromium-browser: command not found
[7902:7902:1215/220418.494435:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/bin/xdg-open: line 862: www-browser: command not found
/bin/xdg-open: line 862: links2: command not found
/bin/xdg-open: line 862: elinks: command not found
/bin/xdg-open: line 862: links: command not found
/bin/xdg-open: line 862: lynx: command not found
/bin/xdg-open: line 862: w3m: command not found
xdg-open: no method available for opening 'telnet://route-server.he.net'

**Comment by SmartFinn** [comment]
@fayooo at first no need to use sudo. As as you see you don't have python installed.

**Comment by fayooo** [comment]
> @fayooo at first no need to use Sudo. As as you see you don't have python installed.

I have solved the python problem by using

sudo alternatives --set python /usr/bin/python2

Now, It is open and working well.

Really thanks a lot for your support and cooperation
