### ISSUE TITLE
Error opening capture

### ISSUE THREAD

**Issue by asembay** [SmartFinn/eve-ng-integration#43]
Hi,
I'm running eve-ng (the latest version  on Ubuntu 18.04.5 LTS server. A browser is firefox. When I click on node interface capture I get this: 

<img width="534" alt="eve-ng error" src="https://user-images.githubusercontent.com/59132648/128485749-3d0817bf-5955-47e7-bbf8-5af820a2dcb7.PNG">

**Comment by SmartFinn** [comment]
The issue doesn't look as related to this project. Please send the issue to eve-ng devs.
