### ISSUE TITLE
Wireshark capture to a remote server  using port forwarding 

### ISSUE THREAD

**Issue by alinbandiu198** [SmartFinn/eve-ng-integration#46]
Hi, 

I am trying to setup the wireshark_wrapper for remote capture on my eve-ng server. My Server is behind a private network so I am using port forward to access it. 
When I try to capture I get the following error: 

![image](https://user-images.githubusercontent.com/63589818/146551251-7a584201-864e-4b9e-abd1-c762a0f63f77.png)

I have tried to add the port by editing the wireshar_wrapper file but not succesfull. 
Please let me know if there;s something to be modified here:
SET S=%1
SET S=%S:capture://=%
FOR /f "tokens=1,2 delims=/ " %%a IN ("%S%") DO SET HOST=%%a&SET INT=%%b
IF "%INT%" == "pnet0" SET FILTER=" not port 22"

ECHO "Connecting to %USERNAME%@%HOST%..."

"C:\Program Files\EVE-NG\plink.exe" -ssh -batch -pw %PASSWORD% %USERNAME%@%HOST% "tcpdump -U -i %INT% -s 0 -w - -%FILTER%" | "C:\Program Files\Wireshark\Wireshark.exe" -k -i -

**Comment by SmartFinn** [comment]
This repo contains integration script for Linux desktop, not Windows. I am not affiliated with the EVE-NG team and the Windows Client Side Pack  in any way.
