### ISSUE TITLE
Wireshark wrapper configuration when using port forward for accesing remote eve-ng server 

### ISSUE THREAD

**Issue by alinbandiu198** [SmartFinn/eve-ng-integration#47]
Hi, 

 Can you please tell me how to setup the wireshark_wrapper when I access my eve-ng server using port forward rules? 
I get end of pipe magic error, I am guessing that the wireshark wrapper does not know the Port and is trying the default one. 
![image](https://user-images.githubusercontent.com/63589818/146670441-7c0d0bfd-bc65-4e71-9b66-b3cf890b0b31.png)

**Comment by SmartFinn** [comment]
https://github.com/SmartFinn/eve-ng-integration/issues/46#issuecomment-996727177
