### ISSUE TITLE
Capture start but no pachets are received on wireshark 

### ISSUE THREAD

**Issue by alinbandiu198** [SmartFinn/eve-ng-integration#48]
Hi, 
I have setup wireshark for eve-ng, the capture start but there are no pachets seen on the capture
![image](https://user-images.githubusercontent.com/63589818/147140568-d7930635-ea0e-4482-b3b5-ea86068f747f.png)
 
Is there a wireshark issue ?

**Comment by SmartFinn** [comment]
https://github.com/SmartFinn/eve-ng-integration/issues/46#issuecomment-996727177
