### ISSUE TITLE
Ubuntu 22.04

### ISSUE THREAD

**Issue by bradk92** [SmartFinn/eve-ng-integration#50]
I tried to install the eve-ng-integration on Ubuntu 22.04 but I get a few errors. The repo doesn't seem to be available and when cloning from git I get the following:
> brad@gengar:~/git/eve-ng-integration$ sudo make install
> mkdir -p "/usr/bin"
> install -m 755 bin/eve-ng-integration /usr/bin/
> install -m 755 bin/eni-rdp-wrapper /usr/bin/
> mkdir -p "/usr/share/applications"
> install -m 644 data/eve-ng-integration.desktop /usr/share/applications/
> install -m 644 data/eni-rdp-wrapper.desktop /usr/share/applications/
> mkdir -p "/usr/share/mime/packages"
> install -m 644 data/eni-rdp-wrapper.xml /usr/share/mime/packages/
> make post-install
> make[1]: Entering directory '/home/brad/git/eve-ng-integration'
> # build cache database of MIME types handled by desktop files
> update-desktop-database -q || true
> # build the Shared MIME-Info database cache
> update-mime-database -n /usr/share/mime || true

When I try instead to just install using the install.sh file (like I've done previously) I get an error about Python
> brad@gengar:~/git/eve-ng-integration$ sh install.sh 
> => Detected distribution: ubuntu 22.04 (debian)
> => Install dependencies...
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Package python is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   python2-minimal:i386 python2:i386 python2-minimal python2 dh-python 2to3 python-is-python3
> 
> E: Package 'python' has no installation candidate

I've even created a global alias of python=python2.7 in case it just needs to find python to execute a script but it's still no good.

**Comment by SmartFinn** [comment]
The installation script and PPA package fixed with 09132e5630c2b382b71b6f8761a50e7ac7763528
