### ISSUE TITLE
Unable to install   eve-ng-integration  in Ubuntu 22 LTS  show dependence error

### ISSUE THREAD

**Issue by raj664** [SmartFinn/eve-ng-integration#51]
** problem  Installing  eve-ng-integration (manual process) ubuntu 22 LTS ** 

1. I was try to install  eve-ng-integration both  PPA & thru script but failed 
 
[github]( https://github.com/SmartFinn/eve-ng-integration#manual-install)

2.  tried manual process  

- 1.download and extract the tarball
- 2.Run make install as root
- 3.Install dependencies (python 2.7)
-after run the install.sh flle it show like this

```
xyz369@s-subuntu:~/App/eve-ng-integration-master$ python2 --version
Python 2.7.18
xyz369@s-subuntu:~/App/eve-ng-integration-master$ sudo ./install.sh 
=> Detected distribution: ubuntu 22.04 (debian)
=> Install dependencies...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal:i386 python2:i386 python2-minimal python2 dh-python 2to3 python-is-python3
E: Package 'python' has no installation candidate
```

 
Plz let me know the how to slove this

**Comment by SmartFinn** [comment]
The installation script and PPA package fixed with 09132e5630c2b382b71b6f8761a50e7ac7763528
