### ISSUE TITLE
Installation - working usage instructions from the point when it is installed missing

### ISSUE THREAD

**Issue by Andrejki** [SmartFinn/eve-ng-integration#53]
Hi.
First of all, thank you for this.

Yet,  I can t get it to work. I don t know from where to get it to work. I ve installed everything. But how to make this work?
Usage instructions would be really helpful for nobs like me.

I hope you are well regarding the Russian/Ukrainian language as people there do not deserve the war.
Kind regards

**Comment by SmartFinn** [comment]
Hey,
The [Demo](https://github.com/SmartFinn/eve-ng-integration#demo) shows the working usage. Sorry, I have no idea what instructions are missing.

You may test it without eve-ng by running the following command in the terminal:

 ```xdg-open 'telnet://route-server.he.net'```

**Comment by Andrejki** [comment]
Thank you. 
Best regards.

**Comment by konstantinosdimos** [comment]
> Hey, The [Demo](https://github.com/SmartFinn/eve-ng-integration#demo) shows the working usage. Sorry, I have no idea what instructions are missing.
> 
> You may test it without eve-ng by running the following command in the terminal:
> 
> `xdg-open 'telnet://route-server.he.net'`

where is the app wth the routers , switches etc. should i install anything else except the repos on readme github page? I am working on ubuntu desktop 22.10
