### ISSUE TITLE
improvement suggestion on readme

### ISSUE THREAD

**Issue by joao-prs** [SmartFinn/eve-ng-integration#58]
In the topic of known issues, in issue 1 **Error Couldn't run /usr/bin/dumpcap in child process: Permission denied when starting Wireshark** it would be interesting to add the command "sudo chmod +x /usr/bin/dumpcap" as a possible alternative to the problem.
Because in my colleagues' test environment, the solutions didn't work for them, but this one did. It would help more people.

**Comment by SmartFinn** [comment]
Binary files in /usr/bin/ already should have executable bit. If is not, please fill issue on bug tracker of your distro.
