### ISSUE TITLE
missing RDP handler

### ISSUE THREAD

**Issue by eczema** [SmartFinn/eve-ng-integration#7]
Hi latest version of EVE also support RDP... 
Hope your project will handle this protocol as well....

Many thanks for your pack.. ( In the name of all Eve Users )

Alain

**Comment by eczema** [comment]
some info to add it:
cat .local/share/applications/mimeapps.list
[Added Associations]
x-scheme-handler/telnet=eve-telnet.desktop
application/x-rdp=eve-rdp.desktop

cat .local/share/applications/eve-rdp.desktop
[Desktop Entry]
Version=1.0
Type=Application
Exec=/usr/local/bin/rdp-handler.sh %u
StartupNotify=true
Terminal=false
MimeType=application/x-rdp
Name=RDP Launcher
Comment=Launch xfreerdp

cat /usr/local/bin/rdp-handler.sh
#!/bin/sh
xfreerdp /v:$(cat "$1" | grep "full address:s" | sed -e 's/.*:s://') /cert-ignore /sec:rdp

**Comment by SmartFinn** [comment]
Added the feature in `v0.0.5`.
