### ISSUE TITLE
telnet does not connect to host:port in pantheon-terminal

### ISSUE THREAD

**Issue by johnsondnz** [SmartFinn/eve-ng-integration#8]
issue with: /usr/bin/eve-ng-integration

testing on command line show that command without single quotes only start telnet it does not initiate the connection to {host} {port} as intended.

> pantheon-terminal -e telnet eveng.it-ninja.xyz 32897
> telnet>

> pantheon-terminal -e 'telnet eveng.it-ninja.xyz 32897'
> Trying 172.22.1.59...
> Connected to eveng.it-ninja.xyz.
> Escape character is '^]'.
> 
> Router>

**Comment by SmartFinn** [comment]
Fixed in [v0.4.1](https://github.com/SmartFinn/eve-ng-integration/releases/tag/v0.4.1)
